// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2a68e26f-44b7-49a0-9e30-11840e896502";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSetColorChange();
void onStepCounterChange();
void onLightSwitchChange();
void onRainNotificationChange();

String weatherCondition;
CloudColor setColor;
float avgNightTemp;
float awakeHours;
float electricityRate;
float homeTemp;
float outdoorTemp;
float sleepHours;
float stepCounter;
CloudColoredLight lightSwitch;
bool rainNotification;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(weatherCondition, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(setColor, READWRITE, ON_CHANGE, onSetColorChange);
  ArduinoCloud.addProperty(avgNightTemp, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(awakeHours, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(electricityRate, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(homeTemp, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(outdoorTemp, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(sleepHours, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(stepCounter, READWRITE, ON_CHANGE, onStepCounterChange);
  ArduinoCloud.addProperty(lightSwitch, READWRITE, ON_CHANGE, onLightSwitchChange);
  ArduinoCloud.addProperty(rainNotification, READWRITE, ON_CHANGE, onRainNotificationChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
